[build]
  command = "npm run build"
  # 🚫 Do NOT set `publish` — let the plugin handle it

[build.environment]
  NODE_VERSION = "18.18.2"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
