[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optional: only if you're serving a static site (no SSR/ISR)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
