[build]
  command = "npm run build"
  publish = "out" # If using next export
  # OR remove 'publish' entirely if using plugin

[build.environment]
  NODE_VERSION = "18.18.2"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
