[build]
  command = "npm run build"
  publish = "out"  # Changed from .next to out for static export
  # No need for functions directory with static export

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

# For static exports, we don't need the Next.js plugin
# as we're using the static export feature

# Handle static assets and client-side routing
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

# Handle root path
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Handle all other paths for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache static assets for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"

# Cache favicons
[[headers]]
  for = "/favicons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"
